# Generated by Django 5.1.2 on 2024-12-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsessionrecord',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutsessionrecord',
            name='plan_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkoutsessionrecord',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
